<a href="https://colab.research.google.com/github/NajlaZuhir/CRM_Data/blob/main/synthetic_fake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generating Data USing Faker

In [ ]:
# !pip install faker
# from transliterate import translit
# !pip install googletrans==4.0.0-rc1

In [ ]:
from faker import Faker
import pandas as pd
import random
from datetime import datetime  # Import datetime class specifically

In [ ]:
jobs = ['Engineer', 'Teacher', 'Doctor', 'Business Owner', 'Student', 'Nurse', "Other"]
cities_in_qatar = ["Doha","Al Wakrah","Al Khor","Umm Salal Mohammed","Al Rayyan","Al Daayen","Madinat ash Shamal"]
list_cuisines = ["Italian", "Japanese", "Mexican", "Indian", "French", "Chinese", "Thai", "Arabic", "Other"]

attractions_in_qatar = ["The Pearl-Qatar","Souq Waqif","Museum of Islamic Art","Katara Cultural Village","Aspire Park",
    "Al Zubarah Fort and Archaeological Site","Doha Corniche","Sheikh Faisal Bin Qassim Al Thani Museum",
    "Katara Beach","Qatar National Museum", "Other"]

event_types = ["Festival","Concert","Exhibition","Football event","Championship event","Doha Expo","Workshop",
    "Doha Tour","Marathon", "Other"]

fake_hobbies = ["Reading","Traveling","Photography","Painting","Cooking","Gardening","Playing musical instruments",
    "Hiking","Swimming","Cycling"]

In [ ]:
# List of feedbacks
# Updated list of feedbacks
feedbacks_list = [
    # Positive Comments
    "Absolutely mesmerized by Qatar's modern architecture and vibrant culture!",
    "The hospitality in Qatar is unparalleled, making my stay truly memorable.",
    "Qatar's rich history comes alive through its museums and heritage sites. A must-visit for history enthusiasts!",
    "The cleanliness and well-maintained infrastructure make Qatar a pleasure to explore.",
    "Incredible shopping experience with a perfect blend of traditional markets and luxury malls.",
    "The cuisine in Qatar is a delightful fusion of flavors, satisfying even the most discerning foodies.",
    "Qatar's commitment to sustainable tourism is commendable â€“ eco-friendly initiatives are evident everywhere.",
    "The warmth and friendliness of the locals create a welcoming atmosphere for tourists.",
    "Qatar's safety measures are top-notch, ensuring a worry-free and secure travel experience.",
    "The desert safari was a thrilling adventure, offering breathtaking views of the dunes.",

    # Negative Comments
    "Traffic congestion in some areas can be frustrating, impacting the overall travel experience.",
    "While the modern side is impressive, the preservation of traditional areas could be better.",
    "Prices in Qatar, especially in tourist areas, can be on the higher side, making it less budget-friendly.",
    "Limited public transportation options make getting around a bit challenging at times.",
    "Some attractions were overcrowded, detracting from the expected tranquility.",
    "Despite efforts, communication in English can be a barrier in certain non-touristy areas.",
    "The weather can be extremely hot, making outdoor activities uncomfortable during certain months.",
    "Lack of clear signage in certain places made navigation confusing for tourists.",
    "Diversity in dining options could be improved, especially for those with specific dietary requirements.",
    "The cultural dress code may be restrictive for some visitors, impacting their comfort.",

    # Neutral Comments
    "The blend of modernity and tradition in Qatar offers a unique and diverse experience for tourists.",
    "The local transportation system is efficient, but improvements could enhance the overall convenience.",
    "Tourist attractions in Qatar cater to a wide range of interests, providing something for everyone.",
    "The variety of accommodations caters to different preferences, from luxury hotels to budget-friendly options.",
    "Qatar's efforts to promote cultural events and festivals add vibrancy to the tourist experience.",
    "Certain areas may lack the hustle and bustle typically associated with tourist destinations.",
    "The availability of information in multiple languages is helpful for international visitors.",
    "Tourist guides play a crucial role in enhancing the understanding of Qatar's history and culture.",
    "The ease of obtaining necessary permits for specific activities contributes to a smooth travel experience.",
    "Local markets offer authentic products, but bargaining skills may come in handy for a better deal."
]

### Dataframe

We have added some new columms

In [ ]:
fake = Faker()
start_id = 1001
reservation_id = 1

data = []

for i in range(5000):
    record = {
        # identification
        "Tourist_ID": start_id,
        "Reservation_ID": reservation_id,
        "passport_number" : fake.random_int(min=100000000, max=999999999),

        # personal info
        "Name": fake.name(),
        "Age": fake.random_int(18, 80),
        "Gender": fake.random_element(elements=('Male', 'Female')),
        "phone_number": fake.phone_number(),
        "Nationality": fake.country(),
        'Nationality_group': random.choice(['GCC', 'Other Arab', 'Other Africa', 'Other Asia inc. Oceania', 'Europe', 'Americans']),
        'family_size': fake.random_int(min=1, max=8),
        'health_insurance': random.choice(['Yes', 'No']),

        # Date
        'Date_Of_Reservation' : fake.date_between(start_date='today', end_date='-5y'),
        'Date_Of_arival' : fake.date_between(start_date='today', end_date='-5y'),
        'arrival_month': fake.month(),

        # Address info
        'country_address': fake.country(),
        'street_address': fake.street_address(),
        'zipcode': fake.zipcode(),
        'state': fake.state(),
        'city': fake.city(),

        # Occupation and financial info
        "Occupation": fake.random_element(elements=jobs),
        'annual_income': fake.random_int(min=20000, max=150000),

        # personal preferences
        "Hobby": fake.random_element(elements=fake_hobbies),
        'payment_preferences': random.choice(['Credit Card', 'PayPal', 'Bank Transfer']),
        'climate_preferences': random.choice(['Tropical', 'Temperate', 'Arctic']),
        "Best_Attraction": fake.random_element(elements=attractions_in_qatar),
        "Cuisine": fake.random_element(elements=list_cuisines),

        # Travel and Transportation info
        "Preferred_Travel_Seasons": fake.random_element(elements=('Spring', 'Summer', 'Autumn', 'Winter')),
        "Modes_of_Travel": fake.random_element(elements=('Sea', 'Land', 'Air')),
        "Frequency_of_Travel": fake.random_element(elements=('Frequent', 'Occasional', 'Rare')),
        "Transportation_Mode": fake.random_element(elements=('Car', 'Bus', 'Metro')),

        # Visit info
        "Num_of_Visits": fake.random_int(min=1, max=7),
        "Days_of_Stay": fake.random_int(5, 60),
        "Random_Event_Type": fake.random_element(elements=event_types),

        # Accommodation info
        "Room_Preferences": fake.random_element(elements=('Single', 'Double', 'Suite')),
        "Hotel_Type": fake.random_element(elements=('Luxury', 'Mid-Range', 'Budget')),
        "Location": fake.random_element(elements=cities_in_qatar),

        # Additional fields (agency concern related)

        "customer_tenure": None, # Placeholder for now
        "package_types": fake.random_element(elements=['Sightseeing Tours', 'Adventure Tours', 'Cultural Tours', 'Beach and Resort Tours', 'Luxury and VIP Tours']),
        "package_cost": None,  # Placeholder for now
        "package_price": None,  # Placeholder for now
        "profit": None,  # Placeholder for now

        # Engagement and feedback
        "Total_Spendings": fake.random_int(min=2000, max=30000),
        "Subscribed_to_Loyalty_Program": fake.boolean(),
        "Rating_of_Services": fake.random_int(min=1, max=5),
        "Feedback": fake.random_element(elements=feedbacks_list),

    }

    record["customer_tenure"] = (datetime.now() - pd.to_datetime(record['Date_Of_Reservation'])).days


    # Set package_cost and package_price based on the selected package_types
    if record["package_types"] == 'Sightseeing Tours':
        record["package_cost"] = 300
        record["package_price"] = 600
    elif record["package_types"] == 'Adventure Tours':
        record["package_cost"] = 500
        record["package_price"] = 1200
    elif record["package_types"] == 'Cultural Tours':
        record["package_cost"] = 400
        record["package_price"] = 800
    elif record["package_types"] == 'Beach and Resort Tours':
        record["package_cost"] = 800
        record["package_price"] = 1500
    elif record["package_types"] == 'Luxury and VIP Tours':
        record["package_cost"] = 1500
        record["package_price"] = 3000

    # Calculate profit (package_price - package_cost)
    record["profit"] = record["package_price"] - record["package_cost"]

    data.append(record)

    reservation_id += 1
    start_id += 1

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV file
df.to_csv("generated_data.csv", index=False)

# Display DataFrame
print(df.head())

   Tourist_ID  Reservation_ID  passport_number              Name  Age  Gender  \
0        1001               1        720909957   Danielle Wilson   34  Female
1        1002               2        327645246      Kevin Thomas   55  Female
2        1003               3        469460822  Katherine Harris   36    Male
3        1004               4        539134464      Emily Wright   49    Male
4        1005               5        666303912     Paul Brown MD   31  Female

           phone_number       Nationality        Nationality_group  \
0      452-558-4948x156           Moldova  Other Asia inc. Oceania
1      445-960-9283x158   Kyrgyz Republic               Other Arab
2         (364)923-9235            Guinea                   Europe
3      904.754.9417x802    Norfolk Island             Other Africa
4  001-903-815-1266x560  Christmas Island                Americans

   family_size  ...            Location customer_tenure  \
0            1  ...           Al Rayyan             379
1            8  ...  Umm Salal Mohammed             972
2            7  ...             Al Khor             917
3            6  ...  Umm Salal Mohammed             683
4            3  ...                Doha            1155

            package_types package_cost package_price profit Total_Spendings  \
0          Cultural Tours          400           800    400            4919
1  Beach and Resort Tours          800          1500    700           27303
2         Adventure Tours          500          1200    700           12431
3          Cultural Tours          400           800    400           11798
4    Luxury and VIP Tours         1500          3000   1500            6555

  Subscribed_to_Loyalty_Program Rating_of_Services  \
0                         False                  1
1                          True                  5
2                         False                  2
3                          True                  2
4                          True                  4

                                            Feedback
0                                  Fantastic service
1  The frequent downtimes are affecting our produ...
2  Absolutely thrilled with the seamless integrat...
3  The software was installed on schedule without...
4                                  Fantastic service

[5 rows x 45 columns]

In [ ]:
df.head()

,Tourist_ID,Reservation_ID,passport_number,Name,Age,Gender,phone_number,Nationality,Nationality_group,family_size,...,Location,customer_tenure,package_types,package_cost,package_price,profit,Total_Spendings,Subscribed_to_Loyalty_Program,Rating_of_Services,Feedback
0,1001,1,720909957,Danielle Wilson,34,Female,452-558-4948x156,Moldova,Other Asia inc. Oceania,1,...,Al Rayyan,379,Cultural Tours,400,800,400,4919,False,1,Fantastic service
1,1002,2,327645246,Kevin Thomas,55,Female,445-960-9283x158,Kyrgyz Republic,Other Arab,8,...,Umm Salal Mohammed,972,Beach and Resort Tours,800,1500,700,27303,True,5,The frequent downtimes are affecting our produ...
2,1003,3,469460822,Katherine Harris,36,Male,(364)923-9235,Guinea,Europe,7,...,Al Khor,917,Adventure Tours,500,1200,700,12431,False,2,Absolutely thrilled with the seamless integrat...
3,1004,4,539134464,Emily Wright,49,Male,904.754.9417x802,Norfolk Island,Other Africa,6,...,Umm Salal Mohammed,683,Cultural Tours,400,800,400,11798,True,2,The software was installed on schedule without...
4,1005,5,666303912,Paul Brown MD,31,Female,001-903-815-1266x560,Christmas Island,Americans,3,...,Doha,1155,Luxury and VIP Tours,1500,3000,1500,6555,True,4,Fantastic service

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Tourist_ID                     5000 non-null   int64
 1   Reservation_ID                 5000 non-null   int64
 2   passport_number                5000 non-null   int64
 3   Name                           5000 non-null   object
 4   Age                            5000 non-null   int64
 5   Gender                         5000 non-null   object
 6   phone_number                   5000 non-null   object
 7   Nationality                    5000 non-null   object
 8   Nationality_group              5000 non-null   object
 9   family_size                    5000 non-null   int64
 10  health_insurance               5000 non-null   object
 11  Date_Of_Reservation            5000 non-null   object
 12  Date_Of_arival                 5000 non-null   object
 13  arrival_month                  5000 non-null   object
 14  country_address                5000 non-null   object
 15  street_address                 5000 non-null   object
 16  zipcode                        5000 non-null   object
 17  state                          5000 non-null   object
 18  city                           5000 non-null   object
 19  Occupation                     5000 non-null   object
 20  annual_income                  5000 non-null   int64
 21  Hobby                          5000 non-null   object
 22  payment_preferences            5000 non-null   object
 23  climate_preferences            5000 non-null   object
 24  Best_Attraction                5000 non-null   object
 25  Cuisine                        5000 non-null   object
 26  Preferred_Travel_Seasons       5000 non-null   object
 27  Modes_of_Travel                5000 non-null   object
 28  Frequency_of_Travel            5000 non-null   object
 29  Transportation_Mode            5000 non-null   object
 30  Num_of_Visits                  5000 non-null   int64
 31  Days_of_Stay                   5000 non-null   int64
 32  Random_Event_Type              5000 non-null   object
 33  Room_Preferences               5000 non-null   object
 34  Hotel_Type                     5000 non-null   object
 35  Location                       5000 non-null   object
 36  customer_tenure                5000 non-null   int64
 37  package_types                  5000 non-null   object
 38  package_cost                   5000 non-null   int64
 39  package_price                  5000 non-null   int64
 40  profit                         5000 non-null   int64
 41  Total_Spendings                5000 non-null   int64
 42  Subscribed_to_Loyalty_Program  5000 non-null   bool
 43  Rating_of_Services             5000 non-null   int64
 44  Feedback                       5000 non-null   object
dtypes: bool(1), int64(14), object(30)
memory usage: 1.7+ MB